### ISSUE TITLE
NextAuth HS256 client settings

### ISSUE THREAD

**Issue by codercatdev** [FusionAuth/fusionauth-example-nextjs-single-sign-on#1]
NextAuth expects RS256, By default FusionAuth default tenant is set to HS256.

![image](https://github.com/FusionAuth/fusionauth-example-nextjs-single-sign-on/assets/3102249/2d3fc5fc-029c-406a-ba4f-b606c6cf2516)

```
https://next-auth.js.org/errors#oauth_callback_error unexpected JWT alg received, expected RS256, got: HS256 {
  error: RPError: unexpected JWT alg received, expected RS256, got: HS256
      at Client.validateJWT (/Users/ccd/web/FusionAuth/fusionauth-example-nextjs-single-sign-on/app/node_modules/.pnpm/openid-client@5.4.2/node_modules/openid-client/lib/client.js:890:13)
      at Client.validateIdToken (/Users/ccd/web/FusionAuth/fusionauth-example-nextjs-single-sign-on/app/node_modules/.pnpm/openid-client@5.4.2/node_modules/openid-client/lib/client.js:745:60)
      at Client.callback (/Users/ccd/web/FusionAuth/fusionauth-example-nextjs-single-sign-on/app/node_modules/.pnpm/openid-client@5.4.2/node_modules/openid-client/lib/client.js:488:18)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async oAuthCallback (/Users/ccd/web/FusionAuth/fusionauth-example-nextjs-single-sign-on/app/node_modules/.pnpm/next-auth@4.19.2_next@13.1.6_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/lib/oauth/callback.js:129:16)
      at async Object.callback (/Users/ccd/web/FusionAuth/fusionauth-example-nextjs-single-sign-on/app/node_modules/.pnpm/next-auth@4.19.2_next@13.1.6_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/routes/callback.js:52:11)
      at async AuthHandler (/Users/ccd/web/FusionAuth/fusionauth-example-nextjs-single-sign-on/app/node_modules/.pnpm/next-auth@4.19.2_next@13.1.6_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/index.js:201:28)
      at async NextAuthHandler (/Users/ccd/web/FusionAuth/fusionauth-example-nextjs-single-sign-on/app/node_modules/.pnpm/next-auth@4.19.2_next@13.1.6_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/next/index.js:24:19)
      at async /Users/ccd/web/FusionAuth/fusionauth-example-nextjs-single-sign-on/app/node_modules/.pnpm/next-auth@4.19.2_next@13.1.6_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/next/index.js:60:32
      at async Object.apiResolver (/Users/ccd/web/FusionAuth/fusionauth-example-nextjs-single-sign-on/app/node_modules/.pnpm/next@13.1.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/api-utils/node.js:372:9)
      at async DevServer.runApi (/Users/ccd/web/FusionAuth/fusionauth-example-nextjs-single-sign-on/app/node_modules/.pnpm/next@13.1.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:488:9)
      at async Object.fn (/Users/ccd/web/FusionAuth/fusionauth-example-nextjs-single-sign-on/app/node_modules/.pnpm/next@13.1.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:751:37)
      at async Router.execute (/Users/ccd/web/FusionAuth/fusionauth-example-nextjs-single-sign-on/app/node_modules/.pnpm/next@13.1.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/router.js:253:36)
      at async DevServer.run (/Users/ccd/web/FusionAuth/fusionauth-example-nextjs-single-sign-on/app/node_modules/.pnpm/next@13.1.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:384:29)
      at async DevServer.run (/Users/ccd/web/FusionAuth/fusionauth-example-nextjs-single-sign-on/app/node_modules/.pnpm/next@13.1.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/dev/next-dev-server.js:743:20)
      at async DevServer.handleRequest (/Users/ccd/web/FusionAuth/fusionauth-example-nextjs-single-sign-on/app/node_modules/.pnpm/next@13.1.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:322:20) {
    name: 'OAuthCallbackError',
    code: undefined
  },
  providerId: 'fusionauth',
  message: 'unexpected JWT alg received, expected RS256, got: HS256'
}
```

**Comment by vcampitelli** [comment]
Closed in favor of adding a note to the README file in 6799093428d1a52fc7cbca3546a14426ba008e4f.

Also see https://github.com/FusionAuth/fusionauth-example-nextjs-single-sign-on/pull/2#issuecomment-1570015295
